package coingecko.constant

object Currency {
    // Fiat
    const val AED = "aed"
    const val ARS = "ars"
    const val AUD = "aud"
    const val BDT = "bdt"
    const val BHD = "bhd"
    const val BMD = "bmd"
    const val BRL = "brl"
    const val CAD = "cad"
    const val CHF = "chf"
    const val CLP = "clp"
    const val CNY = "cny"
    const val CZK = "czk"
    const val DKK = "dkk"
    const val EUR = "eur"
    const val GBP = "gbp"
    const val HKD = "hkd"
    const val HUF = "huf"
    const val IDR = "idr"
    const val ILS = "ils"
    const val INR = "inr"
    const val JPY = "jpy"
    const val KRW = "krw"
    const val KWD = "kwd"
    const val LKR = "lkr"
    const val MMK = "mmk"
    const val MXN = "mxn"
    const val MYR = "myr"
    const val NOK = "nok"
    const val NZD = "nzd"
    const val PHP = "php"
    const val PKR = "pkr"
    const val PLN = "pln"
    const val RUB = "rub"
    const val SAR = "sar"
    const val SEK = "sek"
    const val SGD = "sgd"
    const val THB = "thb"
    const val TRY = "try"
    const val TWD = "twd"
    const val UAH = "uah"
    const val USD = "usd"
    const val VEF = "vef"
    const val VND = "vnd"
    const val XAG = "xag"
    const val XAU = "xau"
    const val XDR = "xdr"
    const val ZAR = "zar"

    // crypto
    const val BNB = "bnb"
    const val EOS = "eos"
    const val BTC = "btc"
    const val BCH = "bch"
    const val ETH = "eth"
    const val LTC = "ltc"
    const val XLM = "xlm"
    const val XRP = "xrp"
}
